---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml

- name: Linux UFW
  hosts: all
  become: true

  # vars:
  #   the ufw config needs to be set in the inventory hosts

  roles:
    - ansibleguy.linux_ufw
