---

- name: UFW | Fail if no rules are defined
  ansible.builtin.fail:
    msg: 'You must define at least one rule to set-up'
  when: ufw_rules == None or ufw_rules|length == 0

- name: UFW | Install package
  ansible.builtin.apt:
    name: ['ufw']
    state: present

- name: UFW | Set defaults
  ansible.builtin.template:
    src: 'templates/etc/default/ufw.j2'
    dest: '/etc/default/ufw'
    owner: 'root'
    group: 'root'
    mode: 0644
  when: configure_ufw_basics
  notify: reload_ufw

- name: UFW | Stateless rules
  ansible.builtin.import_tasks: stateless.yml
  when:
    - (ufw_reset_rules is defined and ufw_reset_rules) or (ufw_stateless is defined and ufw_stateless)
    - ufw_rules is defined
    - ufw_rules | length > 0

- name: UFW | Checking ssh rule
  ansible.builtin.import_tasks: rule/ssh.yml
  when: configure_ufw_ssh_rule

- name: UFW | Stateful rules
  ansible.builtin.import_tasks: stateful.yml
  when:
    - (ufw_reset_rules is defined and not ufw_reset_rules) or (ufw_stateful is defined and ufw_stateful)
    - ufw_rules is defined
    - ufw_rules | length > 0

- name: UFW | Set logging
  community.general.ufw:
    logging: "{{ ufw_config.logging | default(default_ufw_config.logging) }}"
  when: configure_ufw_basics
  notify: reload_ufw

- name: UFW | Enable ufw
  community.general.ufw:
    state: enabled
