---

- name: UFW | Stateful | Processing rules to add
  include_tasks: rule/main.yml
  args:
      apply:
        vars:
          delete_rule: false
  with_dict: "{{ ufw_rules }}"
  loop_control:
    loop_var: rule
  when: >
    (rule.value.state is defined and rule.value.state == 'present') or
    (rule.value.present is defined and rule.value.present) or
    (rule.value.state is undefined and rule.value.present is undefined)

- name: UFW | Stateful | Processing rules to delete
  include_tasks: rule/main.yml
  args:
      apply:
        vars:
          delete_rule: true
  with_dict: "{{ ufw_rules }}"
  loop_control:
    loop_var: rule
  when: >
    (rule.value.state is defined and rule.value.state == 'absent') or
    (rule.value.present is defined and not rule.value.present)
